### ISSUE TITLE
Trusting NVF

### ISSUE THREAD

**Issue by slavingia** [getmovement/getmovement.github.io#15]
We need to do a much better job of communicating (beyond the use cases of our API):

• The types of folks that will have access to this data
• Security measures
• How we will vet users
• Privacy
• Doxxing?
• Cost
• Communicating to those that have been stalked

Please chime in in the comments on ideas/concerns/and more. I'll be working on a new website that will address all of this stuff (and more!) this coming week and beyond.

From @gesa:

> what restrictions will exist on the data, what actions one must take to access it, add it to the README, add it to a wiki, add it to the site.

**Comment by JakeStevens** [comment]
I think the question of trust bolsters the idea of an "credit report" that was proposed. VAN, Nation Builder, etc don't allow to control your data, we could allow it.

**Comment by gesa** [comment]
To get an idea where others are coming from, i urge you to check out a site like <http://www.crashoverridenetwork.com/>. Its purpose is to give support to people to have been harassed, doxed, stalked, or worse. There's also a huge "resources" section with steps to take to erase your personal information from the internet for the purpose of protecting yourself.

Check out Crash Override, get yourself into that headspace, and consider what reassurances you would want to see when it comes to your data being out there. I wasn't kidding when i said [this is why i don't vote](https://twitter.com/gesa/status/837440220760924162). i even [got interviewed](http://blog.votingwars.news21.com/2016/07/26/security-concerns-about-voter-rolls-keeps-outspoken-feminist-away-from-polls/) about that this summer.

**Comment by joshsmith** [comment]
Thanks! That's a really helpful resource for someone coming this without much preexisting knowledge.
