### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by slavingia** [getmovement/getmovement.github.io#5]
Add progress bar to replace line of text

**Comment by slavingia** [comment]
This will be done once we have enough states for it to look 👍 

which will be around 10 or so.

**Comment by joshsmith** [comment]
Can you post screenshot in here?

**Comment by slavingia** [comment]
![pasted image at 2016_11_20 05_14 pm](https://cloud.githubusercontent.com/assets/74396/20515853/504dd04c-b048-11e6-93eb-3ecb7c2a849e.png)
