### ISSUE TITLE
Convert front-end to Ember

### ISSUE THREAD

**Issue by slavingia** [getmovement/getmovement.github.io#6]

**Comment by slavingia** [comment]
@JoshSmith do you know when you'll be able to do this? deciding whether i should add to the website soonish (upcoming week) or wait until after to avoid merge conflicts/confusion.

**Comment by joshsmith** [comment]
@slavingia just to clarify, I think we were going to write the front-end web app in Ember and the backend Elixir; don't think we need Elixir just yet but the Ember side I can try to throw up by mid-week.

**Comment by slavingia** [comment]
ah cool, yea.

**Comment by slavingia** [comment]
ping on this

**Comment by joshsmith** [comment]
@slavingia sorry I am slammed. Trying to cram ~100 hours of work into the next 7 days somehow. I might need until just before Xmas to actually get to this.

Apologies for delays here.

**Comment by slavingia** [comment]
no problem that'll work.

**Comment by slavingia** [comment]
i'll keep as-is. small enough and not a lot of changes, not worth it imo.
